# Generated by Django 4.2.7 on 2023-11-15 13:34

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 13, 34, 17, 203761)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 13, 34, 56, 157676, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
