# Generated by Django 4.2.7 on 2023-11-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_answer_questionvote_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionvote',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_votes', to='app.question'),
        ),
    ]
